version: "2.2"

services:
  photosort:
    image: tomhomewood/photosort:latest
    container_name: photosort
    restart: unless-stopped
    network_mode: none
    environment:
      - PHOTOSORT_MONITOR_CHANGES=false
      - PHOTOSORT_DEBUG=true
      - PHOTOSORT_DRY_RUN=true
    volumes:
      - /home/tom/photos/input:/photos/input
      - /home/tom/photos/output:/photos/output
      - /home/tom/photos/quarantine:/photos/quarantine